Flask_2/app/models.py
from app import db
from datetime import datetime
import re 

from flask_security import UserMixin, RoleMixin


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags', 
                    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
    )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    
    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()
    
    
    tags = db.relationship('Tag', secondary = post_tags, backref=db.backref('posts', lazy='dynamic'))
    
    
    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
            
    
    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)
    
    
class Tag(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))
    
    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)
        
    def __repr__(self):
        return '<Tag id: {}, name: {}>'.format(self.id, self.name)

## FLASK SECURITY ##
role_user = db.Table('role_user',
                    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
    )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=role_user, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

Flask_2/app/posts/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

Flask_2/app/app.py
from flask import Flask, redirect, url_for, request
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore, Security, current_user

app = Flask(__name__)
app.config.from_object(Configuration)


db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


##ADMIN
from models import * 
class MixinAdmin:
    def is_accessible(self):
        return current_user.has_role('admin')
    
    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url ))
    
class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)

class PostAdminView(MixinAdmin, BaseModelView):
    form_columns = ['title', 'body', 'tags']

class TagAdminView(MixinAdmin, BaseModelView):
    form_columns = ['name', 'posts']

class AdminView(MixinAdmin, ModelView):
    pass

class HomeAdminView(MixinAdmin, AdminIndexView):
    pass

    
admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))
admin.add_view(AdminView(User, db.session))
admin.add_view(AdminView(Role, db.session))

##FLASK SECURITY 
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

Flask_2/app/main.py
from app import app
import view
from app import db


from posts.blueprint import posts

app.register_blueprint(posts, url_prefix='/blog')

if (__name__ == "__main__"):
    app.run(debug=True)

Flask_2/app/posts/blueprint.py
from flask import Blueprint, render_template, redirect, url_for
from models import Post, Tag
from app import db
from flask import request

from .forms import PostForm
from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == "POST":
        title = request.form['title']
        body = request.form['body']
        
        post = Post(title=title, body=body)
        
        try:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('posts.index'))
        except:
            return "Error Method Create"
    else:
        form = PostForm()
        return render_template('posts/create_post.html', form=form)
    

@posts.route('/<slug>/edit/', methods=["POST", "GET"])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    
    if request.method == "POST":
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        
        return redirect(url_for('posts.post_details', slug=post.slug))
    else:
        form = PostForm(obj=post)
        return render_template('posts/edit.html', post=post, form=form)

    
@posts.route('/')
def index():
    search = request.args.get('search')
    
    page = request.args.get('page')
    
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    
    if search:
        posts = Post.query.filter(Post.title.contains(search) | Post.body.contains(search))
    else:
        posts = Post.query.order_by(Post.created.desc())
        
    pages = posts.paginate(page=page, per_page=5)
    
    return render_template('posts/index.html', data=posts, pages=pages)


@posts.route('/<slug>')
def post_details(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', data=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', data=posts, tag=tag)

Flask_2/app/templates/index.html
{% extends 'wrapper.html' %}
{% block body %}
    <h1 class="container">Index</h1>
{% endblock %}

Flask_2/app/templates/posts/create_post.html
{% extends 'wrapper.html' %}
{% block body %}
   <div class="container">
        <h1>Create</h1>    
        <form action="{{ url_for('posts.create_post') }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <button class="btn btn-success" type="submit" role="button">Create</button>
        </form>
   </div>
{% endblock %}

Flask_2/app/templates/posts/edit.html
{% extends 'wrapper.html' %}
{% block body %}
   <div class="container">
        <h1>Edit</h1>    
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <button class="btn btn-success" type="submit" role="button">Edit</button>
        </form>
   </div>
{% endblock %}

Flask_2/app/templates/posts/index.html
{% extends 'wrapper.html' %}
{% block body %}
    <h1 class="container">BluePrint</h1>
    <ul>
        {% for el in pages.items %}
        <li class="mt-2">
            <a href="{{ url_for('posts.post_details', slug=el.slug) }}">{{ el.title }}</a>
        </li>
        {% endfor %}
    </ul>
    <nav class="container-fluid">
      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="./?page={{pages.prev_num}}" {% if not pages.has_prev %} style="display: none;" {% endif %}>
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        
        {% for page in pages.iter_pages() %}
            <li  {% if page == pages.page %} class="page-item active" {% else %} class="page-item" {% endif %}><a class="page-link" href="./?page={{page}}">{{page}}</a></li>
        {% endfor %}
        
        <li class="page-item">
          <a class="page-link" href="./?page={{pages.next_num}}" {% if not pages.has_next %} style="display: none;" {% endif %}>
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
{% endblock %}

Flask_2/app/templates/posts/post_detail.html
{% extends 'wrapper.html' %}
{% block body %}
    <h1 class="container">{{ data.title }}</h1>
    <div class="tags_container container">
        {% for tag in tags %}
            <span class="badge badge-success"><a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></span>
        {% endfor %}
    </div>
    <h4 class="container">{{ data.body }}</h4>
{% endblock %}

Flask_2/app/templates/posts/tag_detail.html
{% extends 'wrapper.html' %}
{% block body %}
    <span><h3> Name of the tag: "{{ tag.name }}" .</h3></span>
    <div class="posts-container mt-4">
        {% for post in data %}
        <span class="alert alert-primary"><a href="{{ url_for('posts.post_details', slug=post.slug) }}">{{ post.title }}</a></span>
            <span class="alert alert-info mx-2">{{ post.body }}</span>
            <span class="alert alert-warning">{{ post.id }}</span>
        {% endfor %}
    </div>
{% endblock %}

Flask_2/app/templates/security/login_user.html
{% extends "wrapper.html" %}
{% block body %}
   <div class="container col-4">
    {% from "security/_macros.html" import render_field_with_errors, render_field %}
    {% include "security/_messages.html" %}
    <h1>{{ _('Login') }}</h1>
    <form class="mt-4" action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
        {{ login_user_form.hidden_tag() }}
        {{ render_field_with_errors(login_user_form.email, class="form-control") }}
        {{ render_field_with_errors(login_user_form.password, class="form-control") }}
        {{ render_field_with_errors(login_user_form.remember) }}
        {{ render_field(login_user_form.next) }}
        {{ render_field(login_user_form.submit, class="btn btn-success") }}
    </form>
    {% include "security/_menu.html" %}
</div>
{% endblock %}

Flask_2/app/templates/wrapper.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Flask_Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Flask_2</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{{ url_for('main') }}">Flask</a>
        <a class="p-2 text-dark" href="{{ url_for('posts.index') }}">Blog</a>
        <a class="p-2 text-dark" href="{{ url_for('posts.create_post') }} ">Create</a>
      </nav>
        {% if current_user.has_role('admin') %}
          <a class="btn btn-outline-primary" href="/admin">Admin</a>
        {% endif %}
      <form class="form-inline my-2 my-lg-0 ml-5" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" value="{{ request.args.get('search', '') }}">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    {% block body %}
    
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>